# Red Agent Configuration

# Environment configuration
env:
  name: "HydraRedEnv"
  target_host: "web-app"
  target_ports: [5000, 5432]
  max_steps_per_episode: 100

# Agent configuration
agent:
  type: "PPO"
  learning_rate: 0.0003
  gamma: 0.99
  lambda: 0.95
  kl_coeff: 0.2
  clip_param: 0.3
  vf_clip_param: 10.0
  entropy_coeff: 0.01
  train_batch_size: 4000
  sgd_minibatch_size: 128
  num_sgd_iter: 10
  
# Action space configuration
actions:
  # Port scanning actions
  - name: "scan_port"
    params: ["port_number"]
    description: "Scan a specific port on the target"
    
  # Brute force actions
  - name: "brute_force_login"
    params: ["username", "password"]
    description: "Attempt to login with specific credentials"
    
  # SQL injection actions
  - name: "sql_injection"
    params: ["endpoint", "payload"]
    description: "Attempt SQL injection on a specific endpoint"
    
  # Path traversal actions
  - name: "path_traversal"
    params: ["endpoint", "path"]
    description: "Attempt path traversal on a specific endpoint"

# Observation space configuration
observations:
  - name: "port_status"
    type: "dict"
    description: "Status of scanned ports (open/closed)"
    
  - name: "login_attempts"
    type: "int"
    description: "Number of login attempts made"
    
  - name: "successful_exploits"
    type: "dict"
    description: "Record of successful exploits"
    
  - name: "blocked_attempts"
    type: "dict"
    description: "Record of attempts blocked by Blue Agent"

# Reward configuration
rewards:
  port_scan_success: 0.1
  login_success: 1.0
  sql_injection_success: 2.0
  path_traversal_success: 2.0
  blocked_attempt: -0.5
  step_penalty: -0.01
